### ISSUE TITLE
Hard-coded router address in GroveWeatherPi.py

### ISSUE THREAD

**Issue by cshotton** [switchdoclabs/SDL_Pi_GroveWeatherPi#2]
There is a hard-coded IP address for the user's router address in the GroveWeatherPi.py file. This should be an item in config.py. Not everyone uses a consumer grade router with default settings. The software hangs when this IP address cannot be pinged.

**Comment by switchdoclabs** [comment]
Added configuration variables for the WLAN Present Detection in config.py.  You can now disable WLAN Detection.
