### ISSUE TITLE
DS3231 initialization disabled

### ISSUE THREAD

**Issue by cshotton** [switchdoclabs/SDL_Pi_GroveWeatherPi#3]
Line 243 of GroveWeatherPi.py is commented out by default. This prevents the realtime clock from ever being updated. This should be config.py item at a minimum. Since the Raspi normally uses a NTP client to set its own clock, simply comparing the system time to the DS3231 time should indicate whether or not the clock chip needs to be initialized, eliminating the need to "comment out this line after the clock has been initialized."

**Comment by switchdoclabs** [comment]
Excellent Point.  Changed.

SDL
