### ISSUE TITLE
crcpython2 not installed

### ISSUE THREAD

**Issue by richardtheb** [switchdoclabs/SDL_Pi_GroveWeatherPi#4]
Hey al, just upgraded to this version on my weather station, running on a Pi 3. When I start GroveWeatherPi.py, I get the following error:

`Traceback (most recent call last):
  File "GroveWeatherPi.py", line 557, in <module>
    import crcpython2
ImportError: No module named crcpython2`

I am assuming that crcpython2 is an add-on or something similar. Where do I get that from?

**Comment by switchdoclabs** [comment]
File added to Archive.  Silly me.

SDL

**Comment by richardtheb** [comment]
Heh, redownloaded the package and it worked fine this time.
