### ISSUE TITLE
error found in python script

### ISSUE THREAD

**Issue by miloit** [switchdoclabs/SDL_Pi_GroveWeatherPi#6]
Hello i get this error:

`[Errno 121] Remote I/O error
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/SDL_Pi_GroveWeatherPi/GroveWeatherPi.py", line 1056, in sampleSunAirPlus
    busvoltage1 = sunAirPlus.getBusVoltage_V(LIPO_BATTERY_CHANNEL)
  File "./SDL_Pi_INA3221/SDL_Pi_INA3221.py", line 149, in getBusVoltage_V
    value = self._getBusVoltage_raw(channel)
  File "./SDL_Pi_INA3221/SDL_Pi_INA3221.py", line 131, in _getBusVoltage_raw
    value = self._read_register_little_endian(INA3221_REG_BUSVOLTAGE_1+(channel -1) *2)
  File "./SDL_Pi_INA3221/SDL_Pi_INA3221.py", line 108, in _read_register_little_endian
    result = self._bus.read_word_data(self._addr,register) & 0xFFFF`

**Comment by switchdoclabs** [comment]
You have not connected your SunAirPlus correctly.   Try "i2cdetect -y 1" and see if it is connected.

If you are using a 4 port Mux, go to the SDL_Pi_TCA9545 sub directory and run the test located there.   Carefully check each bus to see what I2C devices are connected.  You probably won't see the AM2315.  That is normal.

SDL

**Comment by miloit** [comment]
`pi@weatherstation:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: 40 -- -- -- -- -- -- -- 48 -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- 57 -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- -- 
70: -- -- -- 73 -- -- -- 77     `

**Comment by switchdoclabs** [comment]
Check it against the documentation.  We really can't read the information you have given us.  Clearly use the TCA9545 test.

**Comment by miloit** [comment]
[http://www.switchdoc.com/forums/topic/some-problems/](http://www.switchdoc.com/forums/topic/some-problems/)

**Comment by miloit** [comment]
INA3221 is active in bus 2 address 40

**Comment by miloit** [comment]
Whats wrong then?

**Comment by miloit** [comment]
Any news?
