### ISSUE TITLE
SI1145 showing only 0

### ISSUE THREAD

**Issue by dsplice** [switchdoclabs/SDL_Pi_GroveWeatherPi#7]
When running the SI1145 simpletest.py, the SI1145 returns correct readings.  When attempting to run through the main GroveWeatherPi.py, sensor only shows 0's.  

I am not running a MUX, device is directly connected to a Pi2Grover board.  

Output indicates that the sensor is detected as being present.
[simpletest.py-output.txt](https://github.com/switchdoclabs/SDL_Pi_GroveWeatherPi/files/1163666/simpletest.py-output.txt)
[GroveWeatherPi-output.txt](https://github.com/switchdoclabs/SDL_Pi_GroveWeatherPi/files/1163667/GroveWeatherPi-output.txt)

**Comment by switchdoclabs** [comment]
Believe it or not, this issue has come up again on version 3.12 and we will be looking at it.

**Comment by jrm964** [comment]
Was this issue ever resolved?  I still get 0 value on the SI1145.  I'm using the latest version 3.17
